# standard jekyll stuff
permalink: /:year/:month/:title.html
markdown: rdiscount
exclude:
 - Rakefile
 - config.rb

# configuration required for some pages
domain: stevector.com
title: stevector.com
author: stevector
email: steve@stevepersch.com

# configuration third-party integration.

github:
  username: stevector

twitter:
  username: stevector

# @todo, fix before live
# disqus:
#   id: 

google_analytics:
  account: UA-42048647-1
